### ISSUE TITLE
不使用python2去评估模型

### ISSUE THREAD

**Issue by zhaoguoqing12** [czczup/FAST#4]
我是用python3评估模型,得到以下结果，差距不大。需要稍改下评估代码。
您是否采用python3评估，差距大吗？
sh eval_tt.sh
Precision:_0.8999034749034738_______/Recall:_0.8521778584392002/Hmean:_0.8753906584715039

**Comment by czczup** [comment]
我用的还是从pan_pp.pytorch拷过来的评估代码，用python2评估的，用python3能跑通当然也可以

**Comment by zhaoguoqing12** [comment]
> 我用的还是从pan_pp.pytorch选过来的评价码，用python2评价的，用python3能跑通当然也可以


> 我用的还是从pan_pp.pytorch选过来的评价码，用python2评价的，用python3能跑通当然也可以

OK 了解啦
